### ISSUE TITLE
Crash 1.19.1

### ISSUE THREAD

**Issue by PaladinFallen** [PotassiumMC/thorium#17]
### Expected behavior

Minecraft to load

### Observed/Actual behavior

Minecraft does load and crashes

### Steps/models to reproduce

Have MC version 1.19.1

### Other

[00:01:39] [main/WARN]: Mod resolution failed
[00:01:39] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED thorium 1.3.1 {depends minecraft @ [1.19]}, ROOT_FORCELOAD_SINGLE thorium 1.3.1]
[00:01:39] [main/INFO]: Reason: [HARD_DEP thorium 1.3.1 {depends minecraft @ [1.19]}]
[00:01:39] [main/INFO]: Fix: add [], remove [], replace [[thorium 1.3.1] -> add:thorium 1 ([(-?,?)])]
[00:01:39] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'thorium' (thorium) 1.3.1 with any version that is compatible with:
		 - minecraft 1.19.1
Unmet dependency listing:
	 - Mod 'thorium' (thorium) 1.3.1 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]

**Comment by NoahvdAa** [comment]
thorium still has to be updated for 1.19.1. I’m currently on vacation but I’ll do it as soon as I’m back :)

**Comment by NoahvdAa** [comment]
1.19.2 support has now been added in 038b775, a release will be out shortly
